import os
import json
import random
from datetime import datetime, timedelta
from typing import List, Dict, Tuple
from collections import Counter

import numpy as np
import pandas as pd

# ============================================================
# PATHS / CONSTANTS
# ============================================================

CONFIG_PATH = os.path.join("output", "config.json")
RAW_DIR = os.path.join("output", "raw")


# ============================================================
# BASIC HELPERS
# ============================================================

def ensure_dir(path: str) -> None:
    """Create directory if it does not exist."""
    os.makedirs(path, exist_ok=True)


def load_config(path: str = CONFIG_PATH) -> dict:
    """Load configuration generated by Module A."""
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Config file not found at {path}. Run Module A first."
        )
    with open(path, "r") as f:
        return json.load(f)


def save_raw_csv(name: str, rows: List[Dict]) -> None:
    """
    Save a list of dicts to CSV under output/raw.
    Example: name='customers' -> output/raw/customers.csv
    """
    ensure_dir(RAW_DIR)
    df = pd.DataFrame(rows)
        # For reproducibility of column order
    out_path = os.path.join(RAW_DIR, f"{name}.csv")
    df.to_csv(out_path, index=False)
    print(f"[OK] Saved raw file: {out_path} ({len(df)} rows)")


def random_choice_from_distribution(dist: Dict[str, float]) -> str:
    """
    Given a dictionary {value: weight}, return one value using the weights.
    Uses random.choices for clarity.
    """
    keys = list(dist.keys())
    weights = list(dist.values())
    return random.choices(population=keys, weights=weights, k=1)[0]


def random_date_in_year_range(start_year: int, end_year: int) -> datetime:
    """Return a random date between 1 Jan start_year and 31 Dec end_year."""
    year = random.randint(start_year, end_year)
    month = random.randint(1, 12)
    # to avoid edge cases with Feb/31, use day <= 28
    day = random.randint(1, 28)
    return datetime(year, month, day)


def add_days(base_date: datetime, mean_days: float, std_days: float) -> datetime:
    """
    Add a random number of days to base_date using a normal distribution.
    Result is clamped to >= 0 days.
    """
    delta = max(int(np.random.normal(mean_days, std_days)), 0)
    return base_date + timedelta(days=delta)


def clamp(value: float, min_value: float, max_value: float) -> float:
    """Clamp a numeric value into [min_value, max_value]."""
    return max(min_value, min(max_value, value))


# ============================================================
# SEVERITY SAMPLER (CLAIMS)
# ============================================================

def sample_severity(product_line: str, sev_cfg: Dict[str, dict]) -> float:
    """
    Sample a claim severity value given line of business and config.
    Supports lognormal, gamma and fixed distributions.
    """
    cfg = sev_cfg[product_line]

    dist = cfg.get("distribution")
    if dist == "lognormal":
        return float(np.random.lognormal(cfg["mu"], cfg["sigma"]))
    if dist == "gamma":
        return float(np.random.gamma(cfg["shape"], cfg["scale"]))
    if dist == "fixed":
        return float(cfg["value"])

    # Fallback, should not happen if config is correct
    return 0.0


# ============================================================
# CUSTOMER ENGINE
# ============================================================

def generate_customers(cfg: dict) -> List[Dict]:
    """
    Generate synthetic customers based on customerModel and geography
    from the configuration.
    Expected columns for Module C:
    - customer_id, age, gender, occupation, marital_status,
      income, bmi, region, state, acquisition_channel

    Extra columns (safe for Module C to ignore):
    - acquisition_date (approx. first contact date)
    """
    num_customers = cfg["portfolio"]["numCustomers"]
    cust_cfg = cfg["customerModel"]
    geo_cfg = cfg["geography"]

    age_min = cust_cfg["age"]["min"]
    age_max = cust_cfg["age"]["max"]

    income_min = cust_cfg["income"]["min"]
    income_max = cust_cfg["income"]["max"]

    bmi_min = cust_cfg["bmi"]["min"]
    bmi_max = cust_cfg["bmi"]["max"]

    gender_dist = cust_cfg["genderDistribution"]
    occupation_dist = cust_cfg["occupationDistribution"]
    marital_dist = cust_cfg["maritalStatusDistribution"]
    acq_dist = cust_cfg["acquisitionChannels"]

    # geography
    regions_map = geo_cfg["regions"]
    region_dist = geo_cfg["regionDistribution"]

    # acquisition date config (approx: a bit before policy effective range)
    policy_date_cfg = cfg["policyModel"]["effectiveDateRange"]
    start_year = policy_date_cfg["startYear"]
    end_year = policy_date_cfg["endYear"]
    acq_start_year = max(start_year - 3, start_year)  # at most 3 years before
    acq_end_year = end_year

    customers: List[Dict] = []

    for i in range(num_customers):
        customer_id = f"CUST-{i+1:07d}"

        # region and state
        region = random_choice_from_distribution(region_dist)
        states_for_region = regions_map[region]
        state = random.choice(states_for_region)

        age = random.randint(age_min, age_max)
        income = random.randint(income_min, income_max)
        bmi = round(random.uniform(bmi_min, bmi_max), 1)

        gender = random_choice_from_distribution(gender_dist)
        occupation = random_choice_from_distribution(occupation_dist)
        marital_status = random_choice_from_distribution(marital_dist)
        acquisition_channel = random_choice_from_distribution(acq_dist)

        acquisition_date = random_date_in_year_range(acq_start_year, acq_end_year)

        customers.append({
            "customer_id": customer_id,
            "age": age,
            "gender": gender,
            "occupation": occupation,
            "marital_status": marital_status,
            "income": income,
            "bmi": bmi,
            "region": region,
            "state": state,
            "acquisition_channel": acquisition_channel,
            "acquisition_date": acquisition_date.strftime("%Y-%m-%d")
        })

    return customers


# ============================================================
# POLICY ENGINE
# ============================================================

def compute_policy_risk_score(
    coverage_amount: float,
    deductible: float,
    cov_cfg: dict,
    product_line: str,
    policy_model_cfg: dict
) -> Tuple[float, str]:
    """
    Compute a simple 0–100 risk_score and qualitative risk_class
    based on coverage, deductible and product-line specific risk factors.
    """
    cov_min = cov_cfg["min"]
    cov_max = cov_cfg["max"]
    # normalize coverage within its range
    coverage_span = max(cov_max - cov_min, 1)
    coverage_ratio = (coverage_amount - cov_min) / coverage_span
    coverage_ratio = clamp(coverage_ratio, 0.0, 1.0)

    # deductible relative to coverage
    deductible_ratio = clamp(deductible / max(coverage_amount, 1.0), 0.0, 1.0)

    # product risk factor from config (optional)
    product_risk_cfg = policy_model_cfg.get("productRiskFactor", {})
    product_risk_boost = float(product_risk_cfg.get(product_line, 0.0))

    # Simple linear model:
    # higher coverage -> more risk
    # lower deductible -> more risk
    base = 20.0
    score = (
        base
        + 50.0 * coverage_ratio
        + 30.0 * (1.0 - deductible_ratio)
        + product_risk_boost
    )
    score = clamp(score, 0.0, 100.0)

    if score < 40:
        risk_class = "LOW"
    elif score < 70:
        risk_class = "MEDIUM"
    else:
        risk_class = "HIGH"

    return score, risk_class


def generate_policies(customers: List[Dict], cfg: dict) -> List[Dict]:
    """
    Generate policies linked to customers.
    Expected columns for Module C:
    - policy_id, customer_id, product_line, coverage_amount,
      deductible, premium_annual, payment_frequency,
      start_date, end_date, region, state, tenure_years

    Extra columns (safe for Module C to ignore):
    - risk_score (0–100), risk_class (LOW/MEDIUM/HIGH)
    """
    product_mix = cfg["productMix"]
    policy_model_cfg = cfg["policyModel"]
    coverage_ranges = policy_model_cfg["coverageRanges"]
    deductible_ranges = policy_model_cfg["deductibleRanges"]
    prem_cfg = cfg["pricingModel"]["technicallyRequiredPremium"]
    date_cfg = policy_model_cfg["effectiveDateRange"]
    payment_freq_dist = policy_model_cfg["paymentFrequencyDistribution"]
    tenure_default_years = policy_model_cfg["tenureYearsDefault"]

    num_customers = len(customers)
    avg_pols = cfg["portfolio"]["avgPoliciesPerCustomer"]
    expected_policies = int(num_customers * avg_pols)

    policies: List[Dict] = []

    for i in range(expected_policies):
        cust = customers[i % num_customers]
        cust_id = cust["customer_id"]
        region = cust["region"]
        state = cust["state"]

        product_line = random_choice_from_distribution(product_mix)

        cov_cfg = coverage_ranges[product_line]
        ded_cfg = deductible_ranges[product_line]
        prem_line_cfg = prem_cfg[product_line]

        coverage_amount = random.randint(cov_cfg["min"], cov_cfg["max"])
        # ensure deductible < coverage_amount and >= 0
        deductible = random.randint(ded_cfg["min"], ded_cfg["max"])
        if deductible >= coverage_amount:
            # cap deductible to at most 50% of coverage as a safety rule
            deductible = int(coverage_amount * 0.5)

        deductible = max(deductible, 0)

        base_rate = prem_line_cfg.get("baseRate", 0.03)
        base_factor = prem_line_cfg.get("baseFactor", 1.5)

        pure_premium = coverage_amount * base_rate
        noise = random.uniform(0.9, 1.1)
        premium_annual = pure_premium * base_factor * noise
        # ensure strictly positive and not absurd vs coverage
        premium_annual = clamp(premium_annual, 50.0, coverage_amount * 0.5)
        premium_annual = round(premium_annual, 2)

        start_dt = random_date_in_year_range(
            date_cfg["startYear"], date_cfg["endYear"]
        )
        # Simple logic: policy term = tenure_default_years * 365 days
        end_dt = start_dt + timedelta(days=365 * tenure_default_years)

        payment_frequency = random_choice_from_distribution(payment_freq_dist)

        # risk scoring
        risk_score, risk_class = compute_policy_risk_score(
            coverage_amount,
            deductible,
            cov_cfg,
            product_line,
            policy_model_cfg
        )

        policy = {
            "policy_id": f"POL-{i+1:07d}",
            "customer_id": cust_id,
            "product_line": product_line,
            "coverage_amount": coverage_amount,
            "deductible": deductible,
            "premium_annual": premium_annual,
            "payment_frequency": payment_frequency,
            "start_date": start_dt.strftime("%Y-%m-%d"),
            "end_date": end_dt.strftime("%Y-%m-%d"),
            "region": region,
            "state": state,
            "tenure_years": tenure_default_years,
            "risk_score": round(risk_score, 2),
            "risk_class": risk_class
        }
        policies.append(policy)

    return policies


# ============================================================
# CLAIMS ENGINE
# ============================================================

def generate_claims(policies: List[Dict], cfg: dict) -> List[Dict]:
    """
    Generate claims based on policies and claim configuration.
    Expected columns for Module C:
    - claim_id, policy_id, customer_id, product_line,
      coverage_amount, claim_amount, deductible, net_paid,
      occurrence_date, report_date, settlement_date,
      region, state, fraud_score, legal_rep_flag

    Mejora clave:
    - frecuencia por póliza con Poisson, con lambda ajustada para
      respetar expectedClaims del config.
    - severidad acotada por cobertura (no siniestros absurdos).
    - fraud_score refinado con risk_class y legal_rep.
    """
    claims_model = cfg["claimsModel"]
    sev_cfg = claims_model["severityCurves"]
    reporting_delay_cfg = claims_model["reportingDelay"]
    settlement_delay_cfg = claims_model["settlementDelay"]

    claim_rate = cfg["portfolio"]["claimRateAnnual"]
    years = cfg["portfolio"]["historyYears"]
    expected_claims = cfg["portfolio"]["expectedClaims"]

    # multiplicadores opcionales
    freq_by_lob = claims_model.get("frequencyByProductLine", {})
    freq_by_region = claims_model.get("frequencyByRegion", {})

    # --------------------------------------------------------
    # 1) Calculamos lambdas sin escalar por póliza
    # --------------------------------------------------------
    raw_lambdas: List[float] = []
    for pol in policies:
        product_line = pol["product_line"]
        region = pol["region"]
        tenure_years = pol.get("tenure_years", years)

        lob_mult = float(freq_by_lob.get(product_line, 1.0))
        reg_mult = float(freq_by_region.get(region, 1.0))

        lam = claim_rate * tenure_years * lob_mult * reg_mult
        raw_lambdas.append(lam)

    # objetivo global similar a expected_claims
    base_total_lambda = len(policies) * claim_rate * years
    target_total_lambda = float(expected_claims or base_total_lambda)

    sum_raw = sum(raw_lambdas)
    scale = target_total_lambda / sum_raw if sum_raw > 0 else 1.0
    scaled_lambdas = [max(l * scale, 0.0) for l in raw_lambdas]

    claims: List[Dict] = []
    claim_counter = 0

    for pol, lam in zip(policies, scaled_lambdas):
        policy_start = datetime.strptime(pol["start_date"], "%Y-%m-%d")
        policy_end = datetime.strptime(pol["end_date"], "%Y-%m-%d")
        total_days = max((policy_end - policy_start).days, 1)

        product_line = pol["product_line"]
        coverage_amount = pol["coverage_amount"]
        deductible = pol["deductible"]
        region = pol["region"]
        state = pol["state"]
        risk_class = pol.get("risk_class", "MEDIUM")

        # número de siniestros para esta póliza
        n_claims = np.random.poisson(lam)
        if n_claims <= 0:
            continue

        for _ in range(n_claims):
            claim_counter += 1

            # occurrence dentro del periodo de cobertura
            offset = random.randint(0, total_days - 1)
            occurrence_dt = policy_start + timedelta(days=offset)

            report_dt = add_days(
                occurrence_dt,
                reporting_delay_cfg["meanDays"],
                reporting_delay_cfg["stdDays"]
            )
            if report_dt < occurrence_dt:
                report_dt = occurrence_dt

            settlement_dt = add_days(
                report_dt,
                settlement_delay_cfg["meanDays"],
                settlement_delay_cfg["stdDays"]
            )
            if settlement_dt < report_dt:
                settlement_dt = report_dt

            # severidad muestral
            raw_claim_amount = sample_severity(product_line, sev_cfg)
            # cap a un múltiplo razonable de la cobertura
            max_factor = claims_model.get("maxSeverityFactor", 1.0)
            max_allowed = coverage_amount * max_factor
            claim_amount = clamp(raw_claim_amount, 0.0, max_allowed)
            claim_amount = round(float(claim_amount), 2)

            net_paid = max(claim_amount - deductible, 0.0)
            net_paid = clamp(net_paid, 0.0, coverage_amount)
            net_paid = round(float(net_paid), 2)

            # fraud score refinado
            report_delay_days = (report_dt - occurrence_dt).days
            severity_ratio = claim_amount / max(coverage_amount, 1.0)

            base_fraud = 20 + report_delay_days * 2 + severity_ratio * 30

            # boost por legal rep y riesgo alto
            legal_rep_flag = random.random() < 0.15
            if legal_rep_flag:
                base_fraud += 10

            if risk_class == "HIGH":
                base_fraud += 5
            elif risk_class == "LOW":
                base_fraud -= 5

            fraud_score = int(round(clamp(base_fraud, 0.0, 100.0)))

            claim = {
                "claim_id": f"CL-{claim_counter:07d}",
                "policy_id": pol["policy_id"],
                "customer_id": pol["customer_id"],
                "product_line": product_line,
                "coverage_amount": coverage_amount,
                "claim_amount": claim_amount,
                "deductible": deductible,
                "net_paid": net_paid,
                "occurrence_date": occurrence_dt.strftime("%Y-%m-%d"),
                "report_date": report_dt.strftime("%Y-%m-%d"),
                "settlement_date": settlement_dt.strftime("%Y-%m-%d"),
                "region": region,
                "state": state,
                "fraud_score": fraud_score,
                "legal_rep_flag": legal_rep_flag
            }
            claims.append(claim)

    print(f"[INFO] Generated {len(claims)} claims (target≈{int(target_total_lambda)})")
    return claims


# ============================================================
# LOSS DEVELOPMENT ENGINE
# ============================================================

def generate_loss_development(claims: List[Dict], cfg: dict) -> List[Dict]:
    """
    Generate simplified loss development rows based on claims.
    Expected columns for Module C:
    - claim_id, product_line, state,
      development_month, incurred_losses, paid_losses

    Nota:
    - con growth rates positivos, incurred y paid son monotónicos crecientes.
    """
    ld_cfg = cfg["pricingModel"]["lossDevelopment"]
    periods = ld_cfg["periods"]
    incurred_growth = ld_cfg["incurredGrowthRate"]
    paid_growth = ld_cfg["paidGrowthRate"]

    rows: List[Dict] = []

    for cl in claims:
        base_incurred = cl["claim_amount"]
        base_paid = cl["net_paid"]
        product_line = cl["product_line"]
        state = cl["state"]

        for m in periods:
            factor_incurred = (1 + incurred_growth) ** (m / 12.0)
            factor_paid = (1 + paid_growth) ** (m / 12.0)

            incurred = base_incurred * factor_incurred
            paid = base_paid * factor_paid

            rows.append({
                "claim_id": cl["claim_id"],
                "product_line": product_line,
                "state": state,
                "development_month": m,
                "incurred_losses": round(float(incurred), 2),
                "paid_losses": round(float(paid), 2)
            })

    return rows


# ============================================================
# QUOTES + UNDERWRITING DECISIONS ENGINE
# ============================================================

def generate_quotes_and_uw_decisions(
    policies: List[Dict],
    cfg: dict
) -> (List[Dict], List[Dict]):
    """
    Generate quotes and underwriting decisions.
    Quotes expected by Module C:
      - quote_id, customer_id, product_line, policy_id_target,
        request_date, quote_date, quote_status, region, state

    UW decisions expected by Module C:
      - quote_id, stp_flag, accepted_flag, bound_flag,
        expired_flag, decline_reason

    Mejora:
    - stp_flag depende de risk_class (más STP en bajo riesgo).
    - flags se recalculan al final a partir de quote_status
      para garantizar consistencia.
    """
    portfolio_cfg = cfg["portfolio"]
    quote_multiplier = portfolio_cfg["quoteMultiplier"]

    uw_cfg = cfg["underwriting"]
    funnel_probs = uw_cfg["funnelProbabilities"]

    num_policies = len(policies)
    expected_quotes = int(num_policies * quote_multiplier)

    quotes: List[Dict] = []
    uw_decisions: List[Dict] = []

    # simple decline reason distribution
    decline_reasons_dist = {
        "Price": 0.35,
        "Risk": 0.25,
        "Documentation": 0.15,
        "Customer Decision": 0.15,
        "Other": 0.10
    }

    base_stp_prob = uw_cfg.get("baseStpProbability", 0.30)

    for i in range(expected_quotes):
        pol = policies[i % num_policies]

        quote_id = f"Q-{i+1:07d}"
        customer_id = pol["customer_id"]
        product_line = pol["product_line"]
        policy_id = pol["policy_id"]
        region = pol["region"]
        state = pol["state"]
        risk_class = pol.get("risk_class", "MEDIUM")

        # request date slightly before or at policy start
        start_dt = datetime.strptime(pol["start_date"], "%Y-%m-%d")
        request_dt = start_dt - timedelta(days=random.randint(0, 60))
        quote_dt = request_dt + timedelta(days=random.randint(0, 5))

        # Funnel probabilities
        requested_to_quoted_p = funnel_probs["Requested_to_Quoted"]
        quoted_to_accepted_p = funnel_probs["Quoted_to_Accepted"]
        accepted_to_bound_p = funnel_probs["Accepted_to_Bound"]
        quoted_to_declined_p = funnel_probs["Quoted_to_Declined"]
        accepted_to_expired_p = funnel_probs["Accepted_to_Expired"]

        # STP as function of risk_class
        if risk_class == "LOW":
            stp_prob = clamp(base_stp_prob * 1.8, 0.0, 0.9)
        elif risk_class == "HIGH":
            stp_prob = clamp(base_stp_prob * 0.5, 0.0, 0.9)
        else:
            stp_prob = base_stp_prob

        stp_flag = random.random() < stp_prob

        decline_reason = ""
        quote_status = "REQUESTED"

        # Step 1: Requested -> Quoted?
        if random.random() <= requested_to_quoted_p:
            # Step 2: Quoted -> Accepted?
            if random.random() <= quoted_to_accepted_p:
                # Step 3: Accepted -> Bound?
                if random.random() <= accepted_to_bound_p:
                    quote_status = "BOUND"
                else:
                    # Maybe expires after acceptance
                    if random.random() <= accepted_to_expired_p:
                        quote_status = "EXPIRED"
                    else:
                        quote_status = "ACCEPTED"
            else:
                # Not accepted, maybe declined
                if random.random() <= quoted_to_declined_p:
                    quote_status = "DECLINED"
                    decline_reason = random_choice_from_distribution(
                        decline_reasons_dist
                    )
                else:
                    quote_status = "QUOTED"
        else:
            # Never quoted, treat as expired request
            quote_status = "EXPIRED"

        # Flags derivados de quote_status para garantizar coherencia
        accepted_flag = quote_status in ("ACCEPTED", "BOUND")
        bound_flag = quote_status == "BOUND"
        expired_flag = quote_status == "EXPIRED"

        quote_row = {
            "quote_id": quote_id,
            "customer_id": customer_id,
            "product_line": product_line,
            "policy_id_target": policy_id,
            "request_date": request_dt.strftime("%Y-%m-%d"),
            "quote_date": quote_dt.strftime("%Y-%m-%d"),
            "quote_status": quote_status,
            "region": region,
            "state": state
        }
        quotes.append(quote_row)

        uw_row = {
            "quote_id": quote_id,
            "stp_flag": stp_flag,
            "accepted_flag": accepted_flag,
            "bound_flag": bound_flag,
            "expired_flag": expired_flag,
            "decline_reason": decline_reason
        }
        uw_decisions.append(uw_row)

    return quotes, uw_decisions


# ============================================================
# RETENTION ENGINE
# ============================================================

def generate_retention(
    customers: List[Dict],
    cfg: dict,
    claims_by_customer: Dict[str, int] | None = None
) -> List[Dict]:
    """
    Generate retention / churn info at customer level.
    Expected columns for Module C:
      - customer_id, status, churn_flag, churn_reason,
        churn_date, campaign_executed, campaign_type,
        responded_flag, retained_after_campaign,
        engagement_score, nps_score

    Mejora:
    - churn_prob ajustada por número de siniestros del cliente.
    """
    churn_cfg = cfg["customerModel"]["churn"]
    base_churn_prob = churn_cfg["baseProbability"]
    churn_reasons_dist = churn_cfg["churnReasons"]

    retention_cfg = cfg["retentionModel"]
    campaign_prob = retention_cfg["campaignProbability"]
    campaign_types_dist = retention_cfg["campaignTypes"]
    engagement_dist = retention_cfg["engagementScoreDistribution"]
    nps_dist = retention_cfg["npsDistribution"]

    policy_date_cfg = cfg["policyModel"]["effectiveDateRange"]
    sim_start_year = policy_date_cfg["startYear"]
    sim_end_year = policy_date_cfg["endYear"]

    rows: List[Dict] = []
    claims_by_customer = claims_by_customer or {}

    for cust in customers:
        customer_id = cust["customer_id"]
        num_claims = claims_by_customer.get(customer_id, 0)

        # Ajuste simple: más siniestros => más probabilidad de churn
        claim_factor = 1.0 + 0.3 * min(num_claims, 5)
        churn_prob = clamp(base_churn_prob * claim_factor, 0.0, 0.9)

        churn_flag = random.random() < churn_prob
        if churn_flag:
            status = "Churned"
            churn_reason = random_choice_from_distribution(churn_reasons_dist)
            churn_date_dt = random_date_in_year_range(sim_start_year, sim_end_year)
            churn_date = churn_date_dt.strftime("%Y-%m-%d")
        else:
            status = "Active"
            churn_reason = ""
            churn_date = ""

        # retention campaign?
        campaign_executed = random.random() < campaign_prob
        if campaign_executed:
            campaign_type = random_choice_from_distribution(campaign_types_dist)
            responded_flag = random.random() < 0.5
            # If already churned, campaign may or may not win back
            retained_after_campaign = responded_flag and (not churn_flag)
        else:
            campaign_type = ""
            responded_flag = False
            retained_after_campaign = False

        engagement_score = random.randint(
            engagement_dist["min"], engagement_dist["max"]
        )
        nps_score = random.randint(nps_dist["min"], nps_dist["max"])

        rows.append({
            "customer_id": customer_id,
            "status": status,
            "churn_flag": churn_flag,
            "churn_reason": churn_reason,
            "churn_date": churn_date,
            "campaign_executed": campaign_executed,
            "campaign_type": campaign_type,
            "responded_flag": responded_flag,
            "retained_after_campaign": retained_after_campaign,
            "engagement_score": engagement_score,
            "nps_score": nps_score
        })

    return rows


# ============================================================
# PRICING SEGMENTS ENGINE
# ============================================================

def generate_pricing_segments(policies: List[Dict], cfg: dict) -> List[Dict]:
    """
    Build simple pricing segments by (product_line, state).
    Expected columns for Module C:
      - segment_id, product_line, state,
        technically_required_premium, our_average_premium,
        market_average_premium, exposure_count

    Nota:
    - segment_id sigue siendo product_line-state para mantener
      compatibilidad con el schema de warehouse.
    """
    if not policies:
        return []

    df_p = pd.DataFrame(policies)

    grouped = df_p.groupby(["product_line", "state"], as_index=False).agg(
        coverage_mean=("coverage_amount", "mean"),
        premium_mean=("premium_annual", "mean"),
        exposure_count=("policy_id", "count")
    )

    trp_cfg = cfg["pricingModel"]["technicallyRequiredPremium"]
    market_var_cfg = cfg["pricingModel"]["marketPremiumVariation"]
    min_var = market_var_cfg["minPercent"]
    max_var = market_var_cfg["maxPercent"]

    rows: List[Dict] = []

    for _, row in grouped.iterrows():
        product_line = str(row["product_line"])
        state = str(row["state"])
        coverage_mean = float(row["coverage_mean"])
        our_avg_premium = float(row["premium_mean"])
        exposure_count = int(row["exposure_count"])

        pl_cfg = trp_cfg[product_line]
        base_rate = pl_cfg.get("baseRate", 0.03)
        base_factor = pl_cfg.get("baseFactor", 1.5)

        pure_premium = coverage_mean * base_rate
        technically_required_premium = pure_premium * base_factor

        # market premium with variation
        variation = random.uniform(min_var, max_var)
        market_average_premium = our_avg_premium * (1 + variation)

        segment_id = f"{product_line}-{state}"

        rows.append({
            "segment_id": segment_id,
            "product_line": product_line,
            "state": state,
            "technically_required_premium": round(technically_required_premium, 2),
            "our_average_premium": round(our_avg_premium, 2),
            "market_average_premium": round(market_average_premium, 2),
            "exposure_count": exposure_count
        })

    return rows


# ============================================================
# MAIN EXECUTION
# ============================================================

def main() -> None:
    print("=== MODULE B — RAW GENERATOR, START ===")

    cfg = load_config()

    # Set seeds for determinism across Python and NumPy
    seed = cfg.get("randomSeed", 12345)
    random.seed(seed)
    np.random.seed(seed)
    print(f"Using random seed: {seed}")

    # 1) Customers
    customers = generate_customers(cfg)
    save_raw_csv("customers", customers)

    # 2) Policies
    policies = generate_policies(customers, cfg)
    save_raw_csv("policies", policies)

    # 3) Claims
    claims = generate_claims(policies, cfg)
    save_raw_csv("claims", claims)

    # 4) Loss Development
    loss_dev = generate_loss_development(claims, cfg)
    save_raw_csv("loss_development", loss_dev)

    # 5) Quotes + UW decisions
    quotes, uw_decisions = generate_quotes_and_uw_decisions(policies, cfg)
    save_raw_csv("quotes", quotes)
    save_raw_csv("uw_decisions", uw_decisions)

    # 6) Retention (ajustada por experiencia de siniestros)
    claims_by_customer = Counter(cl["customer_id"] for cl in claims)
    retention_rows = generate_retention(customers, cfg, claims_by_customer=claims_by_customer)
    save_raw_csv("retention", retention_rows)

    # 7) Pricing segments
    pricing_segments = generate_pricing_segments(policies, cfg)
    save_raw_csv("pricing_segments", pricing_segments)

    print("=== MODULE B — RAW GENERATOR COMPLETE ===")


if __name__ == "__main__":
    main()

